language: node
node_js:
  "4.5.0"
before_script:
  - npm install
  - npm install jshint
script:
  - cp config/startup.yaml.stack-dev ./startup.yaml
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp test
branches:
  only:
    - master
notifications:
  email:
    - sjcarbon@lbl.gov
    - cjmungall@lbl.gov
