language: node
node_js:
  "0.12"
before_script:
  - npm install
script:
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp test
notifications:
  email:
    - sjcarbon@lbl.gov
    - cjmungall@lbl.gov
